name: check-gentx

on:
  push:
    branches:
      - genesis/athens3-reduced-steps
      - cicd/genesis/athens3-reduced-steps
      - main
  pull_request:
    branches:
      - main
      - genesis/athens3-reduced-steps
    paths:
      - 'genesis_files/**'

env:
  # ZETACORED_BINARY: "https://zetachain-external-files.s3.amazonaws.com/binaries/athens3/latest/zetacored-ubuntu"
  # ZETACLIENT_BINARY: "https://zetachain-external-files.s3.amazonaws.com/binaries/athens3/latest/zetaclientd-ubuntu"
  ZETACORED_BINARY: "https://zetachain-external-files.s3.amazonaws.com/binaries/athens3-prerelease/0.0.1/zetacored-ubuntu"
  ZETACLIENT_BINARY: "https://zetachain-external-files.s3.amazonaws.com/binaries/thens3-prerelease/0.0.1/zetaclientd-ubuntu"
  CHAINID: "athens_7001-1"
  KEYRING: "test"
  HOSTNAME: checker

jobs:
  check-gentx:
      runs-on: ["ubuntu-22.04"]
      timeout-minutes: 15
      steps:

      - uses: actions/checkout@v3

      - name: Install Binaries
        run: |
          wget $ZETACORED_BINARY -O zetacored 
          sudo cp zetacored /usr/bin/zetacored
          sudo chmod +x /usr/bin/zetacored
          zetacored version
        
      - name: Check GentX Is Valid
        run: |
          rm -rf ~/.zetacored/ || true
          zetacored init Zetanode --chain-id=$CHAINID
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["staking"]["params"]["bond_denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["crisis"]["constant_fee"]["denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["gov"]["deposit_params"]["min_deposit"][0]["denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["mint"]["params"]["mint_denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["evm"]["params"]["evm_denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.consensus_params["block"]["max_gas"]="10000000"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["gov"]["voting_params"]["voting_period"]="10s"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json

          cp -a genesis_files/os_info/. ~/.zetacored/os_info/
          cp -a genesis_files/gentx/. ~/.zetacored/config/gentx/

          zetacored collect-observer-info
          zetacored add-observer-list
          zetacored collect-gentxs
          zetacored validate-genesis

          zetacored start --trace \
          --minimum-gas-prices=0.0001azeta \
          --json-rpc.api eth,txpool,personal,net,debug,web3,miner \
          --api.enable >> ~/.zetacored/zetacored.log 2>&1  &

          sleep 10
          latest_block_height=$(curl --request GET -sL --url 'localhost:26657/status' --header 'Content-Type: application/json' | jq '.result.sync_info.latest_block_height|tonumber')

          echo "latest_block_height: $latest_block_height"
          if [ "$latest_block_height" -ge 3 ]; then
              echo "SUCCESS"
              echo "gentx and OS_INFO files are valid"
              exit 0
          else
            echo "FAILURE"
              echo "gentx or OS_INFO files are inValid"
              exit 1
          fi
